---
packages_install: []
packages_ubuntu_install:
  - apache2
  - docker-ce
packages_ubuntu_repositories:
  - name: docker
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    uri: https://download.docker.com/linux/ubuntu
    components: stable
    key_url: https://download.docker.com/linux/ubuntu/gpg
    key_id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    enabled: true
packages_ubuntu_pin:
  - package: apache2
    pin: 'release n={{ ansible_distribution_release }}'
    priority: 10
packages_ubuntu_hold:
  - docker-ce
packages_ubuntu_unhold:
  - nano
packages_centos_exclude:
  - emacs
packages_only_security_upgrades: false
packages_ubuntu_update_backports: true
packages_automatic_reboot: true
packages_automatic_reboot_hour: 7
packages_automatic_reboot_minute: 30
packages_services_enabled:
  - rsyslog
packages_services_disabled: []

packages_centos_install:
  - httpd
  - ncdu
packages_centos_repositories:
  - name: epel
    description: epel repository
    baseurl: https://download.fedoraproject.org/pub/epel/{{ ansible_distribution_major_version }}/Everything/x86_64/
    gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
    enabled: true
