driver:
  name: vagrant
  provider:
    name: libvirt
  provision: no
  cachier: machine
  parallel: true
  default_box: 'metno/ubuntu-22.04'

platforms:
  - name: rocky8
    box: metno/rockylinux-8
    box_url: https://vagrant.met.no/meta/rockylinux-8.json
    memory: 2048
    cpus: 2
    instance_raw_config_args:
      - 'vm.synced_folder ".", "/vagrant", disabled: true'
    provider_options:
      qemu_use_session: true
    groups:
      - rocky
  - name: rocky9
    box: metno/rockylinux-9
    box_url: https://vagrant.met.no/meta/rockylinux-9.json
    memory: 2048
    cpus: 2
    instance_raw_config_args:
      - 'vm.synced_folder ".", "/vagrant", disabled: true'
    provider_options:
      qemu_use_session: true
    groups:
      - rocky

provisioner:
  name: ansible
  options:
    user: root

verifier:
  name: ansible
