driver:
  name: vagrant
  provider:
    name: libvirt
  provision: no
  cachier: machine
  parallel: true
  default_box: 'metno/ubuntu-22.04'

platforms:
  - name: packages-noble
    box: metno/ubuntu-24.04
    box_url: https://vagrant.met.no/meta/ubuntu-24.04.json
    memory: 2048
    cpus: 2
    instance_raw_config_args:
      - 'vm.synced_folder ".", "/vagrant", disabled: true'
    provider_options:
      qemu_use_session: true
    groups:
      - ubuntu
  - name: packages-jammy
    box: metno/ubuntu-22.04
    box_url: https://vagrant.met.no/meta/ubuntu-22.04.json
    memory: 2048
    cpus: 2
    instance_raw_config_args:
      - 'vm.synced_folder ".", "/vagrant", disabled: true'
    provider_options:
      qemu_use_session: true
    groups:
      - ubuntu
  - name: packages-focal
    box: metno/ubuntu-20.04
    box_url: https://vagrant.met.no/eol/ubuntu-20.04.json
    memory: 2048
    cpus: 2
    instance_raw_config_args:
      - 'vm.synced_folder ".", "/vagrant", disabled: true'
    provider_options:
      qemu_use_session: true
    groups:
      - ubuntu
  - name: packages-rocky8
    box: metno/rockylinux-8
    box_url: https://vagrant.met.no/meta/rockylinux-8.json
    memory: 2048
    cpus: 2
    instance_raw_config_args:
      - 'vm.synced_folder ".", "/vagrant", disabled: true'
    provider_options:
      qemu_use_session: true
    groups:
      - rocky
  - name: packages-rocky9
    box: metno/rockylinux-9
    box_url: https://vagrant.met.no/meta/rockylinux-9.json
    memory: 2048
    cpus: 2
    instance_raw_config_args:
      - 'vm.synced_folder ".", "/vagrant", disabled: true'
    provider_options:
      qemu_use_session: true
    groups:
      - rocky
  - name: packages-rocky10
    box: metno/rockylinux-10
    box_url: https://vagrant.met.no/meta/rockylinux-10.json
    memory: 2048
    cpus: 2
    instance_raw_config_args:
      - 'vm.synced_folder ".", "/vagrant", disabled: true'
    provider_options:
      qemu_use_session: true
    groups:
      - rocky
  - name: packages-centos7
    box: metno/centos-7
    box_url: https://vagrant.met.no/eol/centos-7.json
    memory: 2048
    cpus: 2
    instance_raw_config_args:
      - 'vm.synced_folder ".", "/vagrant", disabled: true'
    provider_options:
      qemu_use_session: true
    groups:
      - centos
  - name: packages-centos8-stream
    box: metno/centosstream-8
    box_url: https://vagrant.met.no/eol/centosstream-8.json
    memory: 2048
    cpus: 2
    instance_raw_config_args:
      - 'vm.synced_folder ".", "/vagrant", disabled: true'
    provider_options:
      qemu_use_session: true
    groups:
      - centos

provisioner:
  name: ansible
  options:
    user: root

verifier:
  name: ansible
