---
name: Ansible Lint
on: [push, pull_request]

jobs:
  lint:
    name: Run Ansible Lint
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install ansible-core and ansible-lint
      - name: Install ansible-core and ansible-lint
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core~=2.16 ansible-lint~=24.7.0

      # Step 4: Run ansible-lint
      - name: Run ansible-lint
        run: |
          ansible-lint .
